codecov:
  max_report_age: off
  wait_for_ci: no
  require_ci_to_pass: yes
  ci:
    - buildkite

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        target: 80%
        threshold: 15%
        base: auto
        informational: true

    patch:
      default:
        target: 70%
        threshold: 15%
        base: auto

github_checks:
  annotations: true

parsers:
  pass

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "vendor/"
  - "tests/"
  - "build/"
  - "dist/"
