
FROM us-docker.pkg.dev/cookies-eng/public/base/codespaces:v1j@sha256:1df977bb7428c2e9fbb4b22e17510b6e094d293596c59613c53f7974fe7f5246

ENV SHELL=zsh \
    HOME=/home/dev \
    DEVCONTAINER=yes

USER dev
WORKDIR /home/dev
