
FROM us-docker.pkg.dev/cookies-eng/public/base/codespaces:v1j@sha256:a91126297c15c20336e8dd7e274be60950cd2669120254ee142039eb1cb38109

ENV SHELL=zsh \
    HOME=/home/dev \
    DEVCONTAINER=yes

USER dev
WORKDIR /home/dev
