name: "Publish: GitHub Package"
on: push

jobs:
  build-n-publish:
    name: "Build: Python SDK"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      with:
        python-version: 3.9
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/

    - name: Publish distribution 📦 to GCR
      uses: pypa/gh-action-pypi-publish@master
      if: github.repository == 'CookiesCo/sdk-python' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      with:
        password: ${{ secrets.GCR_PYPI_API_TOKEN }}
        repository_url: https://us-python.pkg.dev/cookies-co/sdk-python/
        skip_existing: true

    - name: Publish distribution 📦 to GitHub
      uses: pypa/gh-action-pypi-publish@master
      if: github.repository == 'CookiesCo/sdk-python' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      if: github.repository == 'CookiesCo/sdk-python' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true

    - name: Publish distribution 📦 to PyPI
      if: githb.repository == 'CookiesCo/sdk-python' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip_existing: true

